#! /bin/bash

## downloaded dark gruvbox-gtk3 theme from
## https://github.com/bennetthardwick/gruvbox-gtk
## and move it to /usr/share/themes

## The first argument should be dark or light
## I have named the required files accordingly

## setting up the theme name and term color name
	Term="gruvbox-$1"
	GUI="oomox-gruvbox-$1"	#GTK3 theme location: /usr/share/themes, downloaded from git
# local (in .local/share/themes) themes do not work well, not sure why

if ! [[ -f $HOME/.local/share/xfce4/terminal/colorschemes/$Term.theme ]]
then
    echo "No such colorscheme: $Term"
    exit 1
fi
cd ~/.config/xfce4/terminal
# strip settings from any theme
grep -Fxvf <(cat /usr/share/xfce4/terminal/colorschemes/*.theme) terminalrc > .terminalrc.tmp
grep -v -e Name -e Scheme "$HOME/.local/share/xfce4/terminal/colorschemes/$Term.theme" >> .terminalrc.tmp
cp terminalrc terminalrc.bak

## Applying xfce4-terminal settings on the fly
mv .terminalrc.tmp terminalrc

## Applying the GUI theme on the fly
xfconf-query -c xsettings -p /Net/ThemeName -s $GUI

################################
## Editing vim settings
# Set the vim variable
echo "set background=$1" > $HOME/.vim/vimtheme
# sending remote commands to all running servers to source the new vimrc
# this works under the assumption that I will always run vim in server mode
for f in $(vim --serverlist)	# loop through all the running servers
	do vim --servername $f --remote-send '<ESC>:source ~/.vimrc<CR>'
done


# if request for full update, i.e. awesome restart
## Doesn't work now
##  * We need to find better ways to change color without restarting awesome
##  * We need to find a way to dynamically change the variable colortheme in theme-debdeep.lua
if [ "$2" == "full" ]
then
	## restart awesome after swapping the files
	awmtheme=$HOME/.config/awesome/themes/powerarrow/
	cp $awmtheme/theme-debdeep-$1.lua $awmtheme/theme-debdeep.lua
	echo 'awesome.restart()' | awesome-client 
fi
