#! /bin/bash

## downloaded dark gruvbox-gtk3 theme from
## https://github.com/bennetthardwick/gruvbox-gtk
## and move it to /usr/share/themes


if [ $1 = "dark" ]; then
	Term='gruvbox-dark'
	GUI='oomox-gruvbox-dark'	#GTK3 theme location: /usr/share/themes, downloaded from git
fi
if [ $1 = "light" ]; then
	Term='gruvbox-light'
	GUI='oomox-gruvbox-light'	# Using already install Numix for light theme
fi

# local (in .local/share/themes) themes do not work well, not sure why

if ! [[ -f $HOME/.local/share/xfce4/terminal/colorschemes/$Term.theme ]]
then
    echo "No such colorscheme: $Term"
    exit 1
fi
cd ~/.config/xfce4/terminal
# strip settings from any themes
grep -Fxvf <(cat /usr/share/xfce4/terminal/colorschemes/*.theme) terminalrc > .terminalrc.tmp
grep -v -e Name -e Scheme "$HOME/.local/share/xfce4/terminal/colorschemes/$Term.theme" >> .terminalrc.tmp
cp terminalrc terminalrc.bak
mv .terminalrc.tmp terminalrc

## setting the dark GUI theme
xfconf-query -c xsettings -p /Net/ThemeName -s $GUI


# if request for full update, i.e. awesome restart
if [ $2 = "full" ]; then
	## restart awesome after swapping the files
	awmtheme=$HOME/.config/awesome/themes/powerarrow/
	cp $awmtheme/theme-debdeep-$1.lua $awmtheme/theme-debdeep.lua
	echo 'awesome.restart()' | awesome-client 
fi
